# _config.yml
repository: fmarissel/fmarissel.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

#
# Site settings
#
title: Tech Lead & Développeur Back-end Freelance
name: Fabien Marissel
email: fabien.marissel@f12lconseil.dev
website: https://fmarissel.github.io

about_profile_image: images/f12lconseil_logo_blanc.png
about_content: | # this will include new lines to allow paragraphs
  Tech Lead et Développeur Back-end freelance avec plus de 10 ans d'expérience, spécialisé dans la conception et la réalisation d'applications Java performantes et scalables en environnement Cloud.

#
# Social media links
#
github_username:  fmarissel
twitter_username: fmarissel
linkedin_username: fabien-marissel

#
# Dark mode
# true, false, never
#
darkmode: true

#
# Content
#
content:
  - title: Résumé
    layout: text
    content: | # this will include new lines to allow paragraphs
      J'accompagne mes clients, de la startup au grand groupe (Decathlon, ADEO), dans la modernisation de leurs systèmes d'information en m'appuyant sur des architectures microservices et des pratiques DevOps. Mon objectif est de livrer un code de haute qualité tout en assurant la robustesse et la maintenabilité des solutions.

      Actuellement disponible pour de nouvelles missions en tant que Tech Lead ou Développeur Back-end freelance, je serais ravi d'échanger sur vos projets. Contactez-moi par message privé ou par email : fabien.marissel@f12lconseil.dev.

  - title: Compétences
    layout: text
    content: |
      **Back-end :** Java (11 à 21), Spring Boot, Quarkus, Programmation réactive

      **Cloud & DevOps :** GCP, Kubernetes, AWS, Kafka, Jenkins, Github Actions

      **Architecture :** Microservices, API REST, Intégration continue / Déploiement continu (CI/CD)

  - title: Expérience
    layout: list
    content:
      - layout: left
        title: F12L Conseil
        sub_title: Lead Dev pour Decathlon
        caption: septembre 2022 - Présent
        description: |
          Lead Dev dans l'équipe Customer Growth.
          *   Conception et développement d'une nouvelle solution de marketing automation pour déployer des campagnes d'incitation personnalisées et ciblées.
          *   Mise en place d'une architecture événementielle (Event-Driven) sur GCP avec Kafka pour traiter en temps réel les audiences clients issues de Salesforce Marketing Cloud (SFMC).
          *   Implémentation d'un système de distribution de récompenses sécurisé via des tokens (JWE) et une exposition des services via Cloudflare.

          **Environnement technique :** Java 21, Spring Boot, GCP, Kubernetes, Kafka, SFMC, Datadog, APIM.

      - layout: left
        title: SFEIR
        sub_title: Tech Lead pour ADEO
        caption: janvier 2022 - août 2022
        description: |
          Tech Lead pour la team POPS chez ADEO (plateforme PDP).
          *   Pilotage technique de la création de la plateforme "POPS", une application web destinée à remplacer des processus manuels pour le calcul des prix et des marges fournisseurs.
          *   Conception d'une architecture capable de consommer et de traiter en temps réel l'intégralité du catalogue produits ADEO via des flux de données Kafka.
          *   Création d'un outil de pilotage pour les négociations tarifaires annuelles.

          **Environnement technique :** Java 11, Spring boot, Vault, Kubernetes/Turbine, GCP, Kafka, Github Actions.

      - layout: left
        title: SFEIR
        sub_title: Développeur back-end pour Decathlon
        caption: juillet 2020 - janvier 2022
        description: |
          Développeur Java confirmé pour la team HubMessage chez Decathlon.
          *   Développement d'API REST pour agréger et consolider en temps réel des données hétérogènes (produits, prix, avis clients) via une APIM Gravitee.
          *   Mise à disposition de ces données pour la personnalisation des campagnes email (panier abandonné, etc.) en collaboration avec les intégrateurs sur Salesforce Marketing Cloud (SFMC).
          *   Contribution à la migration des applications de Rancher (AWS) vers Kubernetes (AWS), puis vers Google Kubernetes Engine (GCP).

          **Environnement technique :** Java 14/17, Spring Boot, Quarkus, Programmation réactive, Kubernetes, Helm, AWS, GCP, Salesforce, Gravitee.

      - layout: left
        title: Gfi world
        sub_title: Tech Lead pour BPLS
        caption: août 2019 - mars 2020
        description: |
          Teach Lead chez BPLS sur plusieurs applications monolithiques. Build d'une nouvelle application générée avec JHipster.

          **Environnement technique :** Java 8, Spring boot, Angular 7, JHipster, Liquibase, Swagger, JMS, Gitlab, Jenkins, WebSphere, Oracle DB.

      - layout: left
        title: Gfi world
        sub_title: Lead Developer pour MUTEX
        caption: janvier 2019 - août 2019
        description: |
          Lead developer sur plusieurs applications web pour le client MUTEX (produits d'assurance). Front en Angular 7, architecture en microservices avec Spring Boot pour le back, déploiement sur AWS.

          **Environnement technique :** Java 10, Spring Boot, Rest, Swagger, Feign, Angular 7, Gitlab, Liquibase, MySQL, Microservices.

      - layout: left
        title: Gfi world
        sub_title: Responsable technique EMICA pour EDF
        caption: juillet 2017 - décembre 2018
        description: |
          Responsable technique sur EMICA (Ensemblier, Maintenance et Intégration des Centres d'Appels).

          **Environnement technique :** Java 8, Spring Boot, Thymeleaf, Spring Data JPA, Spring Security, Spring Async, Spring Scheduler, Tomcat, Oracle, PostgreSQL, Jenkins, Artifactory.

      - layout: left
        title: Sopra Steria
        sub_title: Responsable technique RAF pour CIRSO
        caption: juin 2016 - juin 2017
        description: |
          Responsable technique sur GRS, Gestion du RAF (Recouvrement Amiable et Forcé) par Siren.

          **Environnement technique :** Java 8, Spring Boot, Apache CXF, WSDL/SOAP, GWT, MVP4G, JMeter, Eclipse RCP.

      - layout: left
        title: Sopra Steria
        sub_title: Responsable technique CPP2017 pour AIFE
        caption: juin 2015 - juin 2016
        description: |
          Responsable technique sur CPP2017 (Chorus Portail Pro 2017), solution technique mutualisée permettant le dépôt, la réception et la transmission des factures électroniques.

          **Environnement technique :** Java/J2EE, Spring Data JPA, Soap, Apache CXF, Oracle, Tomcat, JFrog, Jenkins, Maven, WSDL/SOAP.

      - layout: left
        title: Sopra Steria
        sub_title: Ingénieur Etudes et Développement Chorus Portail Pro pour AIFE
        caption: mai 2014 - juin 2015
        description: |
          Conception et Développement sur l'application Chorus Portail Pro, un téléservice des mémoires de justice déposés par les fournisseurs de l'Etat.

          **Environnement technique :** Apache Pluto, Struts, JDBC, Maven 3, PostgreSQL, Tomcat, Bootstrap.

      - layout: left
        title: Sopra Steria
        sub_title: Ingénieur développement logiciel GESLAB pour CNRS
        caption: septembre 2010 - mai 2014
        description: |
          Conception et Développement dans le cadre du portage d'une application client lourd en application web.

          **Environnement technique :** Java/J2EE, GWT, Spring, Hibernate, Jboss, Oracle, SWT, Nexus.

  - title: Formation
    layout: list
    content:
      - layout: left
        title: ENSEEIHT
        sub_title: Ingénieur, Informatique et Mathématiques Appliquées
        caption: 2006 - 2010

# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]